server:
  port: 8081

spring:
  main:
    ³allow-bean-definition-overriding: true
    web-application-type: none
  application:
    ui:
      title: Bootiful Java
  dataSource:
    url: jdbc:postgresql://localhost:5432/javafx
    username: postgres
    password: orp101099
  jpa:
    open-in-view: true
    database: POSTGRESQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      show_sql: true
      format_sql: true
  sql:
    init:
      platform: postgres
      mode: always